// Code generated by ent, DO NOT EDIT.

package shipment

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the shipment type in the database.
	Label = "shipment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTrackingNumber holds the string denoting the tracking_number field in the database.
	FieldTrackingNumber = "tracking_number"
	// FieldSenderName holds the string denoting the sender_name field in the database.
	FieldSenderName = "sender_name"
	// FieldReceiverName holds the string denoting the receiver_name field in the database.
	FieldReceiverName = "receiver_name"
	// FieldOrigin holds the string denoting the origin field in the database.
	FieldOrigin = "origin"
	// FieldDestination holds the string denoting the destination field in the database.
	FieldDestination = "destination"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// Table holds the table name of the shipment in the database.
	Table = "shipments"
)

// Columns holds all SQL columns for shipment fields.
var Columns = []string{
	FieldID,
	FieldTrackingNumber,
	FieldSenderName,
	FieldReceiverName,
	FieldOrigin,
	FieldDestination,
	FieldStatus,
	FieldWeight,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
)

// OrderOption defines the ordering options for the Shipment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTrackingNumber orders the results by the tracking_number field.
func ByTrackingNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrackingNumber, opts...).ToFunc()
}

// BySenderName orders the results by the sender_name field.
func BySenderName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSenderName, opts...).ToFunc()
}

// ByReceiverName orders the results by the receiver_name field.
func ByReceiverName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceiverName, opts...).ToFunc()
}

// ByOrigin orders the results by the origin field.
func ByOrigin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrigin, opts...).ToFunc()
}

// ByDestination orders the results by the destination field.
func ByDestination(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDestination, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByWeight orders the results by the weight field.
func ByWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeight, opts...).ToFunc()
}
