// Code generated by ent, DO NOT EDIT.

package shipment

import (
	"shipment-service/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Shipment {
	return predicate.Shipment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Shipment {
	return predicate.Shipment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Shipment {
	return predicate.Shipment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Shipment {
	return predicate.Shipment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Shipment {
	return predicate.Shipment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Shipment {
	return predicate.Shipment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Shipment {
	return predicate.Shipment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Shipment {
	return predicate.Shipment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Shipment {
	return predicate.Shipment(sql.FieldLTE(FieldID, id))
}

// TrackingNumber applies equality check predicate on the "tracking_number" field. It's identical to TrackingNumberEQ.
func TrackingNumber(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEQ(FieldTrackingNumber, v))
}

// SenderName applies equality check predicate on the "sender_name" field. It's identical to SenderNameEQ.
func SenderName(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEQ(FieldSenderName, v))
}

// ReceiverName applies equality check predicate on the "receiver_name" field. It's identical to ReceiverNameEQ.
func ReceiverName(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEQ(FieldReceiverName, v))
}

// Origin applies equality check predicate on the "origin" field. It's identical to OriginEQ.
func Origin(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEQ(FieldOrigin, v))
}

// Destination applies equality check predicate on the "destination" field. It's identical to DestinationEQ.
func Destination(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEQ(FieldDestination, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEQ(FieldStatus, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v float64) predicate.Shipment {
	return predicate.Shipment(sql.FieldEQ(FieldWeight, v))
}

// TrackingNumberEQ applies the EQ predicate on the "tracking_number" field.
func TrackingNumberEQ(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEQ(FieldTrackingNumber, v))
}

// TrackingNumberNEQ applies the NEQ predicate on the "tracking_number" field.
func TrackingNumberNEQ(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldNEQ(FieldTrackingNumber, v))
}

// TrackingNumberIn applies the In predicate on the "tracking_number" field.
func TrackingNumberIn(vs ...string) predicate.Shipment {
	return predicate.Shipment(sql.FieldIn(FieldTrackingNumber, vs...))
}

// TrackingNumberNotIn applies the NotIn predicate on the "tracking_number" field.
func TrackingNumberNotIn(vs ...string) predicate.Shipment {
	return predicate.Shipment(sql.FieldNotIn(FieldTrackingNumber, vs...))
}

// TrackingNumberGT applies the GT predicate on the "tracking_number" field.
func TrackingNumberGT(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldGT(FieldTrackingNumber, v))
}

// TrackingNumberGTE applies the GTE predicate on the "tracking_number" field.
func TrackingNumberGTE(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldGTE(FieldTrackingNumber, v))
}

// TrackingNumberLT applies the LT predicate on the "tracking_number" field.
func TrackingNumberLT(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldLT(FieldTrackingNumber, v))
}

// TrackingNumberLTE applies the LTE predicate on the "tracking_number" field.
func TrackingNumberLTE(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldLTE(FieldTrackingNumber, v))
}

// TrackingNumberContains applies the Contains predicate on the "tracking_number" field.
func TrackingNumberContains(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldContains(FieldTrackingNumber, v))
}

// TrackingNumberHasPrefix applies the HasPrefix predicate on the "tracking_number" field.
func TrackingNumberHasPrefix(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldHasPrefix(FieldTrackingNumber, v))
}

// TrackingNumberHasSuffix applies the HasSuffix predicate on the "tracking_number" field.
func TrackingNumberHasSuffix(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldHasSuffix(FieldTrackingNumber, v))
}

// TrackingNumberEqualFold applies the EqualFold predicate on the "tracking_number" field.
func TrackingNumberEqualFold(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEqualFold(FieldTrackingNumber, v))
}

// TrackingNumberContainsFold applies the ContainsFold predicate on the "tracking_number" field.
func TrackingNumberContainsFold(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldContainsFold(FieldTrackingNumber, v))
}

// SenderNameEQ applies the EQ predicate on the "sender_name" field.
func SenderNameEQ(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEQ(FieldSenderName, v))
}

// SenderNameNEQ applies the NEQ predicate on the "sender_name" field.
func SenderNameNEQ(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldNEQ(FieldSenderName, v))
}

// SenderNameIn applies the In predicate on the "sender_name" field.
func SenderNameIn(vs ...string) predicate.Shipment {
	return predicate.Shipment(sql.FieldIn(FieldSenderName, vs...))
}

// SenderNameNotIn applies the NotIn predicate on the "sender_name" field.
func SenderNameNotIn(vs ...string) predicate.Shipment {
	return predicate.Shipment(sql.FieldNotIn(FieldSenderName, vs...))
}

// SenderNameGT applies the GT predicate on the "sender_name" field.
func SenderNameGT(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldGT(FieldSenderName, v))
}

// SenderNameGTE applies the GTE predicate on the "sender_name" field.
func SenderNameGTE(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldGTE(FieldSenderName, v))
}

// SenderNameLT applies the LT predicate on the "sender_name" field.
func SenderNameLT(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldLT(FieldSenderName, v))
}

// SenderNameLTE applies the LTE predicate on the "sender_name" field.
func SenderNameLTE(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldLTE(FieldSenderName, v))
}

// SenderNameContains applies the Contains predicate on the "sender_name" field.
func SenderNameContains(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldContains(FieldSenderName, v))
}

// SenderNameHasPrefix applies the HasPrefix predicate on the "sender_name" field.
func SenderNameHasPrefix(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldHasPrefix(FieldSenderName, v))
}

// SenderNameHasSuffix applies the HasSuffix predicate on the "sender_name" field.
func SenderNameHasSuffix(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldHasSuffix(FieldSenderName, v))
}

// SenderNameEqualFold applies the EqualFold predicate on the "sender_name" field.
func SenderNameEqualFold(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEqualFold(FieldSenderName, v))
}

// SenderNameContainsFold applies the ContainsFold predicate on the "sender_name" field.
func SenderNameContainsFold(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldContainsFold(FieldSenderName, v))
}

// ReceiverNameEQ applies the EQ predicate on the "receiver_name" field.
func ReceiverNameEQ(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEQ(FieldReceiverName, v))
}

// ReceiverNameNEQ applies the NEQ predicate on the "receiver_name" field.
func ReceiverNameNEQ(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldNEQ(FieldReceiverName, v))
}

// ReceiverNameIn applies the In predicate on the "receiver_name" field.
func ReceiverNameIn(vs ...string) predicate.Shipment {
	return predicate.Shipment(sql.FieldIn(FieldReceiverName, vs...))
}

// ReceiverNameNotIn applies the NotIn predicate on the "receiver_name" field.
func ReceiverNameNotIn(vs ...string) predicate.Shipment {
	return predicate.Shipment(sql.FieldNotIn(FieldReceiverName, vs...))
}

// ReceiverNameGT applies the GT predicate on the "receiver_name" field.
func ReceiverNameGT(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldGT(FieldReceiverName, v))
}

// ReceiverNameGTE applies the GTE predicate on the "receiver_name" field.
func ReceiverNameGTE(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldGTE(FieldReceiverName, v))
}

// ReceiverNameLT applies the LT predicate on the "receiver_name" field.
func ReceiverNameLT(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldLT(FieldReceiverName, v))
}

// ReceiverNameLTE applies the LTE predicate on the "receiver_name" field.
func ReceiverNameLTE(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldLTE(FieldReceiverName, v))
}

// ReceiverNameContains applies the Contains predicate on the "receiver_name" field.
func ReceiverNameContains(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldContains(FieldReceiverName, v))
}

// ReceiverNameHasPrefix applies the HasPrefix predicate on the "receiver_name" field.
func ReceiverNameHasPrefix(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldHasPrefix(FieldReceiverName, v))
}

// ReceiverNameHasSuffix applies the HasSuffix predicate on the "receiver_name" field.
func ReceiverNameHasSuffix(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldHasSuffix(FieldReceiverName, v))
}

// ReceiverNameEqualFold applies the EqualFold predicate on the "receiver_name" field.
func ReceiverNameEqualFold(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEqualFold(FieldReceiverName, v))
}

// ReceiverNameContainsFold applies the ContainsFold predicate on the "receiver_name" field.
func ReceiverNameContainsFold(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldContainsFold(FieldReceiverName, v))
}

// OriginEQ applies the EQ predicate on the "origin" field.
func OriginEQ(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEQ(FieldOrigin, v))
}

// OriginNEQ applies the NEQ predicate on the "origin" field.
func OriginNEQ(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldNEQ(FieldOrigin, v))
}

// OriginIn applies the In predicate on the "origin" field.
func OriginIn(vs ...string) predicate.Shipment {
	return predicate.Shipment(sql.FieldIn(FieldOrigin, vs...))
}

// OriginNotIn applies the NotIn predicate on the "origin" field.
func OriginNotIn(vs ...string) predicate.Shipment {
	return predicate.Shipment(sql.FieldNotIn(FieldOrigin, vs...))
}

// OriginGT applies the GT predicate on the "origin" field.
func OriginGT(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldGT(FieldOrigin, v))
}

// OriginGTE applies the GTE predicate on the "origin" field.
func OriginGTE(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldGTE(FieldOrigin, v))
}

// OriginLT applies the LT predicate on the "origin" field.
func OriginLT(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldLT(FieldOrigin, v))
}

// OriginLTE applies the LTE predicate on the "origin" field.
func OriginLTE(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldLTE(FieldOrigin, v))
}

// OriginContains applies the Contains predicate on the "origin" field.
func OriginContains(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldContains(FieldOrigin, v))
}

// OriginHasPrefix applies the HasPrefix predicate on the "origin" field.
func OriginHasPrefix(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldHasPrefix(FieldOrigin, v))
}

// OriginHasSuffix applies the HasSuffix predicate on the "origin" field.
func OriginHasSuffix(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldHasSuffix(FieldOrigin, v))
}

// OriginEqualFold applies the EqualFold predicate on the "origin" field.
func OriginEqualFold(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEqualFold(FieldOrigin, v))
}

// OriginContainsFold applies the ContainsFold predicate on the "origin" field.
func OriginContainsFold(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldContainsFold(FieldOrigin, v))
}

// DestinationEQ applies the EQ predicate on the "destination" field.
func DestinationEQ(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEQ(FieldDestination, v))
}

// DestinationNEQ applies the NEQ predicate on the "destination" field.
func DestinationNEQ(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldNEQ(FieldDestination, v))
}

// DestinationIn applies the In predicate on the "destination" field.
func DestinationIn(vs ...string) predicate.Shipment {
	return predicate.Shipment(sql.FieldIn(FieldDestination, vs...))
}

// DestinationNotIn applies the NotIn predicate on the "destination" field.
func DestinationNotIn(vs ...string) predicate.Shipment {
	return predicate.Shipment(sql.FieldNotIn(FieldDestination, vs...))
}

// DestinationGT applies the GT predicate on the "destination" field.
func DestinationGT(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldGT(FieldDestination, v))
}

// DestinationGTE applies the GTE predicate on the "destination" field.
func DestinationGTE(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldGTE(FieldDestination, v))
}

// DestinationLT applies the LT predicate on the "destination" field.
func DestinationLT(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldLT(FieldDestination, v))
}

// DestinationLTE applies the LTE predicate on the "destination" field.
func DestinationLTE(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldLTE(FieldDestination, v))
}

// DestinationContains applies the Contains predicate on the "destination" field.
func DestinationContains(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldContains(FieldDestination, v))
}

// DestinationHasPrefix applies the HasPrefix predicate on the "destination" field.
func DestinationHasPrefix(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldHasPrefix(FieldDestination, v))
}

// DestinationHasSuffix applies the HasSuffix predicate on the "destination" field.
func DestinationHasSuffix(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldHasSuffix(FieldDestination, v))
}

// DestinationEqualFold applies the EqualFold predicate on the "destination" field.
func DestinationEqualFold(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEqualFold(FieldDestination, v))
}

// DestinationContainsFold applies the ContainsFold predicate on the "destination" field.
func DestinationContainsFold(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldContainsFold(FieldDestination, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Shipment {
	return predicate.Shipment(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Shipment {
	return predicate.Shipment(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Shipment {
	return predicate.Shipment(sql.FieldContainsFold(FieldStatus, v))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v float64) predicate.Shipment {
	return predicate.Shipment(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v float64) predicate.Shipment {
	return predicate.Shipment(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...float64) predicate.Shipment {
	return predicate.Shipment(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...float64) predicate.Shipment {
	return predicate.Shipment(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v float64) predicate.Shipment {
	return predicate.Shipment(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v float64) predicate.Shipment {
	return predicate.Shipment(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v float64) predicate.Shipment {
	return predicate.Shipment(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v float64) predicate.Shipment {
	return predicate.Shipment(sql.FieldLTE(FieldWeight, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Shipment) predicate.Shipment {
	return predicate.Shipment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Shipment) predicate.Shipment {
	return predicate.Shipment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Shipment) predicate.Shipment {
	return predicate.Shipment(sql.NotPredicates(p))
}
