// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shipment-service/ent/predicate"
	"shipment-service/ent/shipment"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeShipment = "Shipment"
)

// ShipmentMutation represents an operation that mutates the Shipment nodes in the graph.
type ShipmentMutation struct {
	config
	op              Op
	typ             string
	id              *int
	tracking_number *string
	sender_name     *string
	receiver_name   *string
	origin          *string
	destination     *string
	status          *string
	weight          *float64
	addweight       *float64
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*Shipment, error)
	predicates      []predicate.Shipment
}

var _ ent.Mutation = (*ShipmentMutation)(nil)

// shipmentOption allows management of the mutation configuration using functional options.
type shipmentOption func(*ShipmentMutation)

// newShipmentMutation creates new mutation for the Shipment entity.
func newShipmentMutation(c config, op Op, opts ...shipmentOption) *ShipmentMutation {
	m := &ShipmentMutation{
		config:        c,
		op:            op,
		typ:           TypeShipment,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withShipmentID sets the ID field of the mutation.
func withShipmentID(id int) shipmentOption {
	return func(m *ShipmentMutation) {
		var (
			err   error
			once  sync.Once
			value *Shipment
		)
		m.oldValue = func(ctx context.Context) (*Shipment, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Shipment.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withShipment sets the old Shipment of the mutation.
func withShipment(node *Shipment) shipmentOption {
	return func(m *ShipmentMutation) {
		m.oldValue = func(context.Context) (*Shipment, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ShipmentMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ShipmentMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ShipmentMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ShipmentMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Shipment.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTrackingNumber sets the "tracking_number" field.
func (m *ShipmentMutation) SetTrackingNumber(s string) {
	m.tracking_number = &s
}

// TrackingNumber returns the value of the "tracking_number" field in the mutation.
func (m *ShipmentMutation) TrackingNumber() (r string, exists bool) {
	v := m.tracking_number
	if v == nil {
		return
	}
	return *v, true
}

// OldTrackingNumber returns the old "tracking_number" field's value of the Shipment entity.
// If the Shipment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ShipmentMutation) OldTrackingNumber(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTrackingNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTrackingNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTrackingNumber: %w", err)
	}
	return oldValue.TrackingNumber, nil
}

// ResetTrackingNumber resets all changes to the "tracking_number" field.
func (m *ShipmentMutation) ResetTrackingNumber() {
	m.tracking_number = nil
}

// SetSenderName sets the "sender_name" field.
func (m *ShipmentMutation) SetSenderName(s string) {
	m.sender_name = &s
}

// SenderName returns the value of the "sender_name" field in the mutation.
func (m *ShipmentMutation) SenderName() (r string, exists bool) {
	v := m.sender_name
	if v == nil {
		return
	}
	return *v, true
}

// OldSenderName returns the old "sender_name" field's value of the Shipment entity.
// If the Shipment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ShipmentMutation) OldSenderName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSenderName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSenderName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSenderName: %w", err)
	}
	return oldValue.SenderName, nil
}

// ResetSenderName resets all changes to the "sender_name" field.
func (m *ShipmentMutation) ResetSenderName() {
	m.sender_name = nil
}

// SetReceiverName sets the "receiver_name" field.
func (m *ShipmentMutation) SetReceiverName(s string) {
	m.receiver_name = &s
}

// ReceiverName returns the value of the "receiver_name" field in the mutation.
func (m *ShipmentMutation) ReceiverName() (r string, exists bool) {
	v := m.receiver_name
	if v == nil {
		return
	}
	return *v, true
}

// OldReceiverName returns the old "receiver_name" field's value of the Shipment entity.
// If the Shipment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ShipmentMutation) OldReceiverName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReceiverName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReceiverName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReceiverName: %w", err)
	}
	return oldValue.ReceiverName, nil
}

// ResetReceiverName resets all changes to the "receiver_name" field.
func (m *ShipmentMutation) ResetReceiverName() {
	m.receiver_name = nil
}

// SetOrigin sets the "origin" field.
func (m *ShipmentMutation) SetOrigin(s string) {
	m.origin = &s
}

// Origin returns the value of the "origin" field in the mutation.
func (m *ShipmentMutation) Origin() (r string, exists bool) {
	v := m.origin
	if v == nil {
		return
	}
	return *v, true
}

// OldOrigin returns the old "origin" field's value of the Shipment entity.
// If the Shipment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ShipmentMutation) OldOrigin(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOrigin is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOrigin requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOrigin: %w", err)
	}
	return oldValue.Origin, nil
}

// ResetOrigin resets all changes to the "origin" field.
func (m *ShipmentMutation) ResetOrigin() {
	m.origin = nil
}

// SetDestination sets the "destination" field.
func (m *ShipmentMutation) SetDestination(s string) {
	m.destination = &s
}

// Destination returns the value of the "destination" field in the mutation.
func (m *ShipmentMutation) Destination() (r string, exists bool) {
	v := m.destination
	if v == nil {
		return
	}
	return *v, true
}

// OldDestination returns the old "destination" field's value of the Shipment entity.
// If the Shipment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ShipmentMutation) OldDestination(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDestination is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDestination requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDestination: %w", err)
	}
	return oldValue.Destination, nil
}

// ResetDestination resets all changes to the "destination" field.
func (m *ShipmentMutation) ResetDestination() {
	m.destination = nil
}

// SetStatus sets the "status" field.
func (m *ShipmentMutation) SetStatus(s string) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *ShipmentMutation) Status() (r string, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Shipment entity.
// If the Shipment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ShipmentMutation) OldStatus(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *ShipmentMutation) ResetStatus() {
	m.status = nil
}

// SetWeight sets the "weight" field.
func (m *ShipmentMutation) SetWeight(f float64) {
	m.weight = &f
	m.addweight = nil
}

// Weight returns the value of the "weight" field in the mutation.
func (m *ShipmentMutation) Weight() (r float64, exists bool) {
	v := m.weight
	if v == nil {
		return
	}
	return *v, true
}

// OldWeight returns the old "weight" field's value of the Shipment entity.
// If the Shipment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ShipmentMutation) OldWeight(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWeight is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWeight requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWeight: %w", err)
	}
	return oldValue.Weight, nil
}

// AddWeight adds f to the "weight" field.
func (m *ShipmentMutation) AddWeight(f float64) {
	if m.addweight != nil {
		*m.addweight += f
	} else {
		m.addweight = &f
	}
}

// AddedWeight returns the value that was added to the "weight" field in this mutation.
func (m *ShipmentMutation) AddedWeight() (r float64, exists bool) {
	v := m.addweight
	if v == nil {
		return
	}
	return *v, true
}

// ResetWeight resets all changes to the "weight" field.
func (m *ShipmentMutation) ResetWeight() {
	m.weight = nil
	m.addweight = nil
}

// Where appends a list predicates to the ShipmentMutation builder.
func (m *ShipmentMutation) Where(ps ...predicate.Shipment) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ShipmentMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ShipmentMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Shipment, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ShipmentMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ShipmentMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Shipment).
func (m *ShipmentMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ShipmentMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.tracking_number != nil {
		fields = append(fields, shipment.FieldTrackingNumber)
	}
	if m.sender_name != nil {
		fields = append(fields, shipment.FieldSenderName)
	}
	if m.receiver_name != nil {
		fields = append(fields, shipment.FieldReceiverName)
	}
	if m.origin != nil {
		fields = append(fields, shipment.FieldOrigin)
	}
	if m.destination != nil {
		fields = append(fields, shipment.FieldDestination)
	}
	if m.status != nil {
		fields = append(fields, shipment.FieldStatus)
	}
	if m.weight != nil {
		fields = append(fields, shipment.FieldWeight)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ShipmentMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case shipment.FieldTrackingNumber:
		return m.TrackingNumber()
	case shipment.FieldSenderName:
		return m.SenderName()
	case shipment.FieldReceiverName:
		return m.ReceiverName()
	case shipment.FieldOrigin:
		return m.Origin()
	case shipment.FieldDestination:
		return m.Destination()
	case shipment.FieldStatus:
		return m.Status()
	case shipment.FieldWeight:
		return m.Weight()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ShipmentMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case shipment.FieldTrackingNumber:
		return m.OldTrackingNumber(ctx)
	case shipment.FieldSenderName:
		return m.OldSenderName(ctx)
	case shipment.FieldReceiverName:
		return m.OldReceiverName(ctx)
	case shipment.FieldOrigin:
		return m.OldOrigin(ctx)
	case shipment.FieldDestination:
		return m.OldDestination(ctx)
	case shipment.FieldStatus:
		return m.OldStatus(ctx)
	case shipment.FieldWeight:
		return m.OldWeight(ctx)
	}
	return nil, fmt.Errorf("unknown Shipment field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ShipmentMutation) SetField(name string, value ent.Value) error {
	switch name {
	case shipment.FieldTrackingNumber:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTrackingNumber(v)
		return nil
	case shipment.FieldSenderName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSenderName(v)
		return nil
	case shipment.FieldReceiverName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReceiverName(v)
		return nil
	case shipment.FieldOrigin:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOrigin(v)
		return nil
	case shipment.FieldDestination:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDestination(v)
		return nil
	case shipment.FieldStatus:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case shipment.FieldWeight:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWeight(v)
		return nil
	}
	return fmt.Errorf("unknown Shipment field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ShipmentMutation) AddedFields() []string {
	var fields []string
	if m.addweight != nil {
		fields = append(fields, shipment.FieldWeight)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ShipmentMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case shipment.FieldWeight:
		return m.AddedWeight()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ShipmentMutation) AddField(name string, value ent.Value) error {
	switch name {
	case shipment.FieldWeight:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddWeight(v)
		return nil
	}
	return fmt.Errorf("unknown Shipment numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ShipmentMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ShipmentMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ShipmentMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Shipment nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ShipmentMutation) ResetField(name string) error {
	switch name {
	case shipment.FieldTrackingNumber:
		m.ResetTrackingNumber()
		return nil
	case shipment.FieldSenderName:
		m.ResetSenderName()
		return nil
	case shipment.FieldReceiverName:
		m.ResetReceiverName()
		return nil
	case shipment.FieldOrigin:
		m.ResetOrigin()
		return nil
	case shipment.FieldDestination:
		m.ResetDestination()
		return nil
	case shipment.FieldStatus:
		m.ResetStatus()
		return nil
	case shipment.FieldWeight:
		m.ResetWeight()
		return nil
	}
	return fmt.Errorf("unknown Shipment field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ShipmentMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ShipmentMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ShipmentMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ShipmentMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ShipmentMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ShipmentMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ShipmentMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Shipment unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ShipmentMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Shipment edge %s", name)
}
