// Code generated by ent, DO NOT EDIT.

package ent

import (
	"shipment-service/ent/schema"
	"shipment-service/ent/shipment"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	shipmentFields := schema.Shipment{}.Fields()
	_ = shipmentFields
	// shipmentDescStatus is the schema descriptor for status field.
	shipmentDescStatus := shipmentFields[5].Descriptor()
	// shipment.DefaultStatus holds the default value on creation for the status field.
	shipment.DefaultStatus = shipmentDescStatus.Default.(string)
}
