// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"shipment-service/ent/shipment"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Shipment is the model entity for the Shipment schema.
type Shipment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TrackingNumber holds the value of the "tracking_number" field.
	TrackingNumber string `json:"tracking_number,omitempty"`
	// SenderName holds the value of the "sender_name" field.
	SenderName string `json:"sender_name,omitempty"`
	// ReceiverName holds the value of the "receiver_name" field.
	ReceiverName string `json:"receiver_name,omitempty"`
	// Origin holds the value of the "origin" field.
	Origin string `json:"origin,omitempty"`
	// Destination holds the value of the "destination" field.
	Destination string `json:"destination,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Weight holds the value of the "weight" field.
	Weight       float64 `json:"weight,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Shipment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case shipment.FieldWeight:
			values[i] = new(sql.NullFloat64)
		case shipment.FieldID:
			values[i] = new(sql.NullInt64)
		case shipment.FieldTrackingNumber, shipment.FieldSenderName, shipment.FieldReceiverName, shipment.FieldOrigin, shipment.FieldDestination, shipment.FieldStatus:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Shipment fields.
func (_m *Shipment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case shipment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case shipment.FieldTrackingNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tracking_number", values[i])
			} else if value.Valid {
				_m.TrackingNumber = value.String
			}
		case shipment.FieldSenderName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_name", values[i])
			} else if value.Valid {
				_m.SenderName = value.String
			}
		case shipment.FieldReceiverName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field receiver_name", values[i])
			} else if value.Valid {
				_m.ReceiverName = value.String
			}
		case shipment.FieldOrigin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field origin", values[i])
			} else if value.Valid {
				_m.Origin = value.String
			}
		case shipment.FieldDestination:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field destination", values[i])
			} else if value.Valid {
				_m.Destination = value.String
			}
		case shipment.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case shipment.FieldWeight:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				_m.Weight = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Shipment.
// This includes values selected through modifiers, order, etc.
func (_m *Shipment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Shipment.
// Note that you need to call Shipment.Unwrap() before calling this method if this Shipment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Shipment) Update() *ShipmentUpdateOne {
	return NewShipmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Shipment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Shipment) Unwrap() *Shipment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Shipment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Shipment) String() string {
	var builder strings.Builder
	builder.WriteString("Shipment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tracking_number=")
	builder.WriteString(_m.TrackingNumber)
	builder.WriteString(", ")
	builder.WriteString("sender_name=")
	builder.WriteString(_m.SenderName)
	builder.WriteString(", ")
	builder.WriteString("receiver_name=")
	builder.WriteString(_m.ReceiverName)
	builder.WriteString(", ")
	builder.WriteString("origin=")
	builder.WriteString(_m.Origin)
	builder.WriteString(", ")
	builder.WriteString("destination=")
	builder.WriteString(_m.Destination)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteByte(')')
	return builder.String()
}

// Shipments is a parsable slice of Shipment.
type Shipments []*Shipment
