// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shipment-service/ent/shipment"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShipmentCreate is the builder for creating a Shipment entity.
type ShipmentCreate struct {
	config
	mutation *ShipmentMutation
	hooks    []Hook
}

// SetTrackingNumber sets the "tracking_number" field.
func (_c *ShipmentCreate) SetTrackingNumber(v string) *ShipmentCreate {
	_c.mutation.SetTrackingNumber(v)
	return _c
}

// SetSenderName sets the "sender_name" field.
func (_c *ShipmentCreate) SetSenderName(v string) *ShipmentCreate {
	_c.mutation.SetSenderName(v)
	return _c
}

// SetReceiverName sets the "receiver_name" field.
func (_c *ShipmentCreate) SetReceiverName(v string) *ShipmentCreate {
	_c.mutation.SetReceiverName(v)
	return _c
}

// SetOrigin sets the "origin" field.
func (_c *ShipmentCreate) SetOrigin(v string) *ShipmentCreate {
	_c.mutation.SetOrigin(v)
	return _c
}

// SetDestination sets the "destination" field.
func (_c *ShipmentCreate) SetDestination(v string) *ShipmentCreate {
	_c.mutation.SetDestination(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ShipmentCreate) SetStatus(v string) *ShipmentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ShipmentCreate) SetNillableStatus(v *string) *ShipmentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetWeight sets the "weight" field.
func (_c *ShipmentCreate) SetWeight(v float64) *ShipmentCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// Mutation returns the ShipmentMutation object of the builder.
func (_c *ShipmentCreate) Mutation() *ShipmentMutation {
	return _c.mutation
}

// Save creates the Shipment in the database.
func (_c *ShipmentCreate) Save(ctx context.Context) (*Shipment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShipmentCreate) SaveX(ctx context.Context) *Shipment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShipmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShipmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShipmentCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := shipment.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShipmentCreate) check() error {
	if _, ok := _c.mutation.TrackingNumber(); !ok {
		return &ValidationError{Name: "tracking_number", err: errors.New(`ent: missing required field "Shipment.tracking_number"`)}
	}
	if _, ok := _c.mutation.SenderName(); !ok {
		return &ValidationError{Name: "sender_name", err: errors.New(`ent: missing required field "Shipment.sender_name"`)}
	}
	if _, ok := _c.mutation.ReceiverName(); !ok {
		return &ValidationError{Name: "receiver_name", err: errors.New(`ent: missing required field "Shipment.receiver_name"`)}
	}
	if _, ok := _c.mutation.Origin(); !ok {
		return &ValidationError{Name: "origin", err: errors.New(`ent: missing required field "Shipment.origin"`)}
	}
	if _, ok := _c.mutation.Destination(); !ok {
		return &ValidationError{Name: "destination", err: errors.New(`ent: missing required field "Shipment.destination"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Shipment.status"`)}
	}
	if _, ok := _c.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "Shipment.weight"`)}
	}
	return nil
}

func (_c *ShipmentCreate) sqlSave(ctx context.Context) (*Shipment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShipmentCreate) createSpec() (*Shipment, *sqlgraph.CreateSpec) {
	var (
		_node = &Shipment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(shipment.Table, sqlgraph.NewFieldSpec(shipment.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TrackingNumber(); ok {
		_spec.SetField(shipment.FieldTrackingNumber, field.TypeString, value)
		_node.TrackingNumber = value
	}
	if value, ok := _c.mutation.SenderName(); ok {
		_spec.SetField(shipment.FieldSenderName, field.TypeString, value)
		_node.SenderName = value
	}
	if value, ok := _c.mutation.ReceiverName(); ok {
		_spec.SetField(shipment.FieldReceiverName, field.TypeString, value)
		_node.ReceiverName = value
	}
	if value, ok := _c.mutation.Origin(); ok {
		_spec.SetField(shipment.FieldOrigin, field.TypeString, value)
		_node.Origin = value
	}
	if value, ok := _c.mutation.Destination(); ok {
		_spec.SetField(shipment.FieldDestination, field.TypeString, value)
		_node.Destination = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(shipment.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(shipment.FieldWeight, field.TypeFloat64, value)
		_node.Weight = value
	}
	return _node, _spec
}

// ShipmentCreateBulk is the builder for creating many Shipment entities in bulk.
type ShipmentCreateBulk struct {
	config
	err      error
	builders []*ShipmentCreate
}

// Save creates the Shipment entities in the database.
func (_c *ShipmentCreateBulk) Save(ctx context.Context) ([]*Shipment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Shipment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShipmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShipmentCreateBulk) SaveX(ctx context.Context) []*Shipment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShipmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShipmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
