// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shipment-service/ent/predicate"
	"shipment-service/ent/shipment"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShipmentUpdate is the builder for updating Shipment entities.
type ShipmentUpdate struct {
	config
	hooks    []Hook
	mutation *ShipmentMutation
}

// Where appends a list predicates to the ShipmentUpdate builder.
func (_u *ShipmentUpdate) Where(ps ...predicate.Shipment) *ShipmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTrackingNumber sets the "tracking_number" field.
func (_u *ShipmentUpdate) SetTrackingNumber(v string) *ShipmentUpdate {
	_u.mutation.SetTrackingNumber(v)
	return _u
}

// SetNillableTrackingNumber sets the "tracking_number" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableTrackingNumber(v *string) *ShipmentUpdate {
	if v != nil {
		_u.SetTrackingNumber(*v)
	}
	return _u
}

// SetSenderName sets the "sender_name" field.
func (_u *ShipmentUpdate) SetSenderName(v string) *ShipmentUpdate {
	_u.mutation.SetSenderName(v)
	return _u
}

// SetNillableSenderName sets the "sender_name" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableSenderName(v *string) *ShipmentUpdate {
	if v != nil {
		_u.SetSenderName(*v)
	}
	return _u
}

// SetReceiverName sets the "receiver_name" field.
func (_u *ShipmentUpdate) SetReceiverName(v string) *ShipmentUpdate {
	_u.mutation.SetReceiverName(v)
	return _u
}

// SetNillableReceiverName sets the "receiver_name" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableReceiverName(v *string) *ShipmentUpdate {
	if v != nil {
		_u.SetReceiverName(*v)
	}
	return _u
}

// SetOrigin sets the "origin" field.
func (_u *ShipmentUpdate) SetOrigin(v string) *ShipmentUpdate {
	_u.mutation.SetOrigin(v)
	return _u
}

// SetNillableOrigin sets the "origin" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableOrigin(v *string) *ShipmentUpdate {
	if v != nil {
		_u.SetOrigin(*v)
	}
	return _u
}

// SetDestination sets the "destination" field.
func (_u *ShipmentUpdate) SetDestination(v string) *ShipmentUpdate {
	_u.mutation.SetDestination(v)
	return _u
}

// SetNillableDestination sets the "destination" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableDestination(v *string) *ShipmentUpdate {
	if v != nil {
		_u.SetDestination(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ShipmentUpdate) SetStatus(v string) *ShipmentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableStatus(v *string) *ShipmentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *ShipmentUpdate) SetWeight(v float64) *ShipmentUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableWeight(v *float64) *ShipmentUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *ShipmentUpdate) AddWeight(v float64) *ShipmentUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// Mutation returns the ShipmentMutation object of the builder.
func (_u *ShipmentUpdate) Mutation() *ShipmentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ShipmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShipmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ShipmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShipmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ShipmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(shipment.Table, shipment.Columns, sqlgraph.NewFieldSpec(shipment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TrackingNumber(); ok {
		_spec.SetField(shipment.FieldTrackingNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderName(); ok {
		_spec.SetField(shipment.FieldSenderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReceiverName(); ok {
		_spec.SetField(shipment.FieldReceiverName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Origin(); ok {
		_spec.SetField(shipment.FieldOrigin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Destination(); ok {
		_spec.SetField(shipment.FieldDestination, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(shipment.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(shipment.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(shipment.FieldWeight, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shipment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ShipmentUpdateOne is the builder for updating a single Shipment entity.
type ShipmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ShipmentMutation
}

// SetTrackingNumber sets the "tracking_number" field.
func (_u *ShipmentUpdateOne) SetTrackingNumber(v string) *ShipmentUpdateOne {
	_u.mutation.SetTrackingNumber(v)
	return _u
}

// SetNillableTrackingNumber sets the "tracking_number" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableTrackingNumber(v *string) *ShipmentUpdateOne {
	if v != nil {
		_u.SetTrackingNumber(*v)
	}
	return _u
}

// SetSenderName sets the "sender_name" field.
func (_u *ShipmentUpdateOne) SetSenderName(v string) *ShipmentUpdateOne {
	_u.mutation.SetSenderName(v)
	return _u
}

// SetNillableSenderName sets the "sender_name" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableSenderName(v *string) *ShipmentUpdateOne {
	if v != nil {
		_u.SetSenderName(*v)
	}
	return _u
}

// SetReceiverName sets the "receiver_name" field.
func (_u *ShipmentUpdateOne) SetReceiverName(v string) *ShipmentUpdateOne {
	_u.mutation.SetReceiverName(v)
	return _u
}

// SetNillableReceiverName sets the "receiver_name" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableReceiverName(v *string) *ShipmentUpdateOne {
	if v != nil {
		_u.SetReceiverName(*v)
	}
	return _u
}

// SetOrigin sets the "origin" field.
func (_u *ShipmentUpdateOne) SetOrigin(v string) *ShipmentUpdateOne {
	_u.mutation.SetOrigin(v)
	return _u
}

// SetNillableOrigin sets the "origin" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableOrigin(v *string) *ShipmentUpdateOne {
	if v != nil {
		_u.SetOrigin(*v)
	}
	return _u
}

// SetDestination sets the "destination" field.
func (_u *ShipmentUpdateOne) SetDestination(v string) *ShipmentUpdateOne {
	_u.mutation.SetDestination(v)
	return _u
}

// SetNillableDestination sets the "destination" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableDestination(v *string) *ShipmentUpdateOne {
	if v != nil {
		_u.SetDestination(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ShipmentUpdateOne) SetStatus(v string) *ShipmentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableStatus(v *string) *ShipmentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *ShipmentUpdateOne) SetWeight(v float64) *ShipmentUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableWeight(v *float64) *ShipmentUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *ShipmentUpdateOne) AddWeight(v float64) *ShipmentUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// Mutation returns the ShipmentMutation object of the builder.
func (_u *ShipmentUpdateOne) Mutation() *ShipmentMutation {
	return _u.mutation
}

// Where appends a list predicates to the ShipmentUpdate builder.
func (_u *ShipmentUpdateOne) Where(ps ...predicate.Shipment) *ShipmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ShipmentUpdateOne) Select(field string, fields ...string) *ShipmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Shipment entity.
func (_u *ShipmentUpdateOne) Save(ctx context.Context) (*Shipment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShipmentUpdateOne) SaveX(ctx context.Context) *Shipment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ShipmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShipmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ShipmentUpdateOne) sqlSave(ctx context.Context) (_node *Shipment, err error) {
	_spec := sqlgraph.NewUpdateSpec(shipment.Table, shipment.Columns, sqlgraph.NewFieldSpec(shipment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Shipment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, shipment.FieldID)
		for _, f := range fields {
			if !shipment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != shipment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TrackingNumber(); ok {
		_spec.SetField(shipment.FieldTrackingNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderName(); ok {
		_spec.SetField(shipment.FieldSenderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReceiverName(); ok {
		_spec.SetField(shipment.FieldReceiverName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Origin(); ok {
		_spec.SetField(shipment.FieldOrigin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Destination(); ok {
		_spec.SetField(shipment.FieldDestination, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(shipment.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(shipment.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(shipment.FieldWeight, field.TypeFloat64, value)
	}
	_node = &Shipment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shipment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
